services:
  - type: web
    name: ananta-crm-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SESSION_COOKIE_SAMESITE
        value: "None"
      - key: CSRF_COOKIE_SAMESITE
        value: "None"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
