# Generated by Django 6.1 on 2026-09-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. IN', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('currency_code', models.CharField(help_text='ISO 4217, e.g. INR', max_length=3)),
                ('currency_symbol', models.CharField(help_text='e.g. ₹', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'object_id'], name='core_activi_module_12e1e2_idx')],
            },
        ),
    ]
