# Generated by Django 6.1 on 2026-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_numbersequence'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbersequence',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='numbersequence',
            name='key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='numbersequence',
            unique_together={('organization', 'key')},
        ),
    ]
