# Generated by Django 6.1 on 2026-09-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_numbersequence_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(help_text='e.g. AED, USD, EUR, GBP, INR', max_length=3)),
                ('target_currency', models.CharField(help_text='e.g. INR or AED (base currency)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=14)),
                ('market_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=14)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='organizations.organization')),
            ],
            options={
                'ordering': ['source_currency'],
                'unique_together': {('organization', 'source_currency', 'target_currency')},
            },
        ),
    ]
