# Generated by Django 6.1 on 2026-09-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exchangerate'),
        ('organizations', '0004_organization_whatsapp_default_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('order_item', 'Order Line Item'), ('quotation_item', 'Quotation Line Item'), ('costing_item', 'Costing Line Item'), ('product', 'Product / Catalog'), ('client', 'Client'), ('company', 'Company'), ('supplier', 'Supplier'), ('project', 'Project')], max_length=32)),
                ('field_key', models.CharField(help_text="Key stored in JSON extra_data, e.g. 'paper_gsm' or 'hsn_code'", max_length=64)),
                ('label', models.CharField(help_text='Display label shown in forms and table headers', max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Dropdown Selection'), ('date', 'Date'), ('boolean', 'Yes / No (Checkbox)')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text="List of choices if field_type is 'select'")),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_table', models.BooleanField(default=True, help_text='Show as a column in list tables')),
                ('show_in_print', models.BooleanField(default=True, help_text='Include in print / PDF invoice templates')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('organization', 'module', 'field_key')},
            },
        ),
    ]
