# Generated by Django 6.1 on 2026-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_project'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('organization', 'order_no')},
        ),
    ]
