# Generated by Django 6.1 on 2026-09-03 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_currency_code',
            field=models.CharField(default='INR', help_text='Organization base currency at order creation', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_code',
            field=models.CharField(default='INR', help_text='Billing currency of this order', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Conversion rate of 1 currency_code into organization base_currency_code', max_digits=14),
        ),
    ]
