# Generated by Django 6.1 on 2026-09-03 18:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_base_currency_code_order_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount received/collected so far', max_digits=12),
        ),
    ]
