# Generated by Django 6.1 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='columns_config',
            field=models.JSONField(blank=True, default=list, help_text='Extra custom columns beyond product/description/qty/rate, e.g. [{"key": "custom_gsm", "label": "GSM"}]. Values live per-item in OrderItem.extra_data under the same key.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Values for Order.columns_config keys.'),
        ),
    ]
