# Generated by Django 6.1 on 2026-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='e.g. Aje Joie chhe print thai ne', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='project_title',
            field=models.CharField(blank=True, help_text='e.g. Diamond Standy', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance', 'Advance'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
