# Generated by Django 6.1 on 2026-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('suppliers', '0002_remove_supplier_unique_active_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organizations.organization'),
        ),
    ]
