# Generated by Django 6.1 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field attributes for supplier'),
        ),
    ]
