# Generated by Django 6.1 on 2026-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_details',
            field=models.TextField(blank=True, help_text='Product details and categories supplied'),
        ),
    ]
