# Generated by Django 6.1 on 2026-09-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_company_name_supplier_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='file_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('rate_card', 'Rate Card'), ('brochure', 'Brochure')], max_length=20),
        ),
    ]
