# Generated by Django 6.1 on 2026-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplierfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.CharField(choices=[('A', 'Grade A (Top / Best)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Low Priority)')], default='B', help_text='ABC Supplier rating / classification tier', max_length=1),
        ),
    ]
