# Generated by Django 6.1 on 2026-09-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_company_gstin_company_msin_number'),
        ('suppliers', '0007_supplier_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='clients.company'),
        ),
    ]
