# Generated by Django 6.1 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_alter_costing_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='columns_config',
            field=models.JSONField(blank=True, default=list, help_text='Extra custom columns beyond supplier_rate/quantity/client_rate, e.g. [{"key": "custom_wastage", "label": "Wastage %"}]. Values live per-item in CostingItem.extra_data under the same key.'),
        ),
        migrations.AddField(
            model_name='costingitem',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Values for Costing.columns_config keys.'),
        ),
    ]
