# Generated by Django 6.1 on 2026-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_costing_columns_config_costingitem_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='costings/files/'),
        ),
        migrations.AddField(
            model_name='costing',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
