# Generated by Django 6.1 on 2026-09-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_costing_file_costing_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='costings/files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='costing.costing')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
