# Generated by Django 6.1 on 2026-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0007_costingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingfile',
            name='category',
            field=models.CharField(choices=[('catalogue', 'Catalogue'), ('rate_list', 'Rate List')], default='catalogue', max_length=50),
        ),
    ]
