# Generated by Django 6.1 on 2026-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('clients', 'Clients'), ('companies', 'Companies'), ('catalog', 'Products'), ('suppliers', 'Suppliers'), ('projects', 'Projects'), ('orders', 'Orders'), ('quotations', 'Quotations'), ('costing', 'Costing'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings'), ('notifications', 'Notifications')], max_length=32),
        ),
    ]
