# Generated by Django 6.1 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_organization_alter_company_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field attributes for client'),
        ),
        migrations.AddField(
            model_name='company',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field attributes for company'),
        ),
    ]
