# Generated by Django 6.1 on 2026-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='company',
            name='msin_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='MSIN Number'),
        ),
    ]
