# Generated by Django 6.1 on 2026-09-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quotation_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('quotation_date', models.DateField()),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('to_address', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('intro_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('footer_content', models.TextField(blank=True)),
                ('col_qty_label', models.CharField(default='Qty', max_length=50)),
                ('col_rate_label', models.CharField(default='Rate', max_length=50)),
                ('columns_config', models.JSONField(blank=True, default=list, help_text='Extra custom columns beyond description/qty/rate, e.g. [{"key": "custom_size", "label": "Size"}]. Values live per-item in QuotationItem.extra_data under the same key.')),
                ('currency_code', models.CharField(default='INR', help_text="Defaults from the client's country at creation time, editable per-quotation.", max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, help_text='A real column — the legacy app buried this inside the extra_data JSON blob.', null=True, upload_to='quotations/items/')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Values for Quotation.columns_config keys.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
