# Generated by Django 6.1 on 2026-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('quotations', '0002_quotation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('organization', 'quotation_no')},
        ),
    ]
