# Generated by Django 6.1 on 2026-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('quotations', '0003_quotation_organization_alter_quotation_quotation_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='organizations.organization'),
        ),
    ]
