# Generated by Django 6.1 on 2026-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_alter_quotation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='base_currency_code',
            field=models.CharField(default='INR', help_text='Organization base currency at quotation creation', max_length=3),
        ),
        migrations.AddField(
            model_name='quotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Conversion rate of 1 currency_code into organization base_currency_code', max_digits=14),
        ),
    ]
