# Generated by Django 6.1 on 2026-09-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('primary_color', models.CharField(default='#C31432', help_text='Hex, e.g. #C31432', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('default_currency_code', models.CharField(default='INR', max_length=3)),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quotation_prefix', models.CharField(default='QT-', max_length=20)),
                ('quotation_intro', models.TextField(blank=True)),
                ('quotation_terms', models.TextField(blank=True)),
                ('quotation_signature_name', models.CharField(blank=True, max_length=150)),
                ('quotation_designation', models.CharField(blank=True, max_length=150)),
                ('quotation_contact_person', models.CharField(blank=True, max_length=150)),
                ('quotation_background_image', models.ImageField(blank=True, null=True, upload_to='organizations/quotations/')),
                ('quotation_signature_image', models.ImageField(blank=True, null=True, upload_to='organizations/quotations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
