# Generated by Django 6.1 on 2026-09-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_organization_alter_company_organization'),
        ('orders', '0005_order_base_currency_code_order_currency_code_and_more'),
        ('organizations', '0001_initial'),
        ('quotations', '0005_quotation_base_currency_code_quotation_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='e.g. billing@company.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_from_name',
            field=models.CharField(blank=True, help_text='e.g. Ananta Graphics', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='587 for TLS, 465 for SSL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(help_text='Email address or phone number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('logged', 'Logged (WhatsApp)')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='clients.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='organizations.organization')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='quotations.quotation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
