# Generated by Django 6.1 on 2026-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_admin_email',
            field=models.EmailField(blank=True, help_text='Recipient email address for internal admin alerts', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_new_order',
            field=models.BooleanField(default=True, help_text='Send email alert when staff books a new order'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_order_delivered',
            field=models.BooleanField(default=False, help_text='Send email alert when order is marked delivered'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_payment_received',
            field=models.BooleanField(default=True, help_text='Send email alert when order payment is received/paid'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_quote_accepted',
            field=models.BooleanField(default=True, help_text='Send email alert when a quote is accepted/won'),
        ),
    ]
