# Generated by Django 6.1 on 2026-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_notify_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='whatsapp_default_country_code',
            field=models.CharField(default='+91', help_text='Default dial code, e.g. +91', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Official WhatsApp Business phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_order_template',
            field=models.TextField(blank=True, help_text='Custom default template for order confirmation'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_payment_template',
            field=models.TextField(blank=True, help_text='Custom default template for payment reminders'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_quote_template',
            field=models.TextField(blank=True, help_text='Custom default template for quotations'),
        ),
    ]
