# Generated by Django 6.1 on 2026-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_whatsapp_default_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order_prefix',
            field=models.CharField(blank=True, default='AG/', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='quotation_prefix',
            field=models.CharField(default='AG/', max_length=20),
        ),
    ]
