# Generated by Django 6.1 on 2026-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_order_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_logo',
            field=models.ImageField(blank=True, help_text='Dedicated logo for PDF exports and printed reports', null=True, upload_to='organizations/reports/'),
        ),
    ]
